name: Build and Validate
on:
  pull_request:

jobs:
  ubuntu:
    name: Ubuntu Cross
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.properties.outputs.version }}
      changelog: ${{ steps.properties.outputs.changelog }}
    steps:
      - name: Fetch Sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - name: Install OS Dependencies
        # The base setup should already have many of these installed,
        # but this makes it explicit.
        # Even with this explicit golang version install, the dependencies
        # install into the standard go home directory, rather than the
        # version directory.
        # This uses 'zig' to perform cross-compiling with CGO.
        run: |
          set +x
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y \
              libbtrfs-dev libassuan-dev libgpgme-dev \
              zip \
              golang \
              make
          go install golang.org/dl/go1.26.8@latest
          $HOME/go/bin/go1.26.8 download
          export GOROOT=$($HOME/go/bin/go1.26.8 env GOROOT)
          export PATH=$GOROOT/bin:$HOME/go/bin:$PATH
          make go-dependencies
          echo $GOROOT/bin
          ls $GOROOT/bin
          echo $HOME/go/bin
          ls $HOME/go/bin

      - name: Build & Test
        run: |
          export GOROOT=$($HOME/go/bin/go1.26.8 env GOROOT)
          export PATH=$GOROOT/bin:$HOME/go/bin:$PATH
          make all

  ubuntu-no-cgo:
    name: Ubuntu No Cgo
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.properties.outputs.version }}
      changelog: ${{ steps.properties.outputs.changelog }}
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3
      
      - name: Install OS Dependencies
        # The base setup should already have many of these installed,
        # but this makes it explicit.
        # Even with this explicit golang version install, the dependencies
        # install into the standard go home directory, rather than the
        # version directory.
        run: |
          set +x
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y \
              golang \
              make \
              ca-certificates \
              openssl
          go install golang.org/dl/go1.26.8@latest
          $HOME/go/bin/go1.26.8 download
          export GOROOT=$($HOME/go/bin/go1.26.8 env GOROOT)
          export PATH=$GOROOT/bin:$HOME/go/bin:$PATH
          make go-dependencies
          echo $GOROOT/bin
          ls $GOROOT/bin
          echo $HOME/go/bin
          ls $HOME/go/bin

      - name: Build & Test
        run: |
          export GOROOT=$($HOME/go/bin/go1.26.8 env GOROOT)
          export PATH=$GOROOT/bin:$HOME/go/bin:$PATH
          make CGO_ENABLED=0 all
