name: Build and Validate
on:
    pull_request:

jobs:
    ubuntu:
        name: Ubuntu
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.properties.outputs.version }}
            changelog: ${{ steps.properties.outputs.changelog }}
        steps:
            - name: Fetch Sources
              uses: actions/checkout@v3
            
            - name: Install OS Dependencies
              # The base setup should already have many of these installed,
              # but this makes it explicit.
              run: |
                sudo apt-get update
                DEBIAN_FRONTEND=noninteractive sudo apt-get install -y \
                    libbtrfs-dev \
                    golang \
                    make

            - name: Build & Test
              run: |
                make all
