name: Build and Validate
on:
  pull_request:

env:
  GO_VERSION: 1.26.8

jobs:
  ubuntu-cross:
    name: Ubuntu Cross
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - name: Install OS dependencies
        # The base setup should already have many of these installed, but this makes it explicit.
        run: |
          set +x
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y \
              libbtrfs-dev libassuan-dev libgpgme-dev \
              zip \
              golang \
              make

      - name: Install Go and its dependencies
        # Install the right Go version + the build-specific dependencies.
        run: |
          go install golang.org/dl/go${GO_VERSION}@latest
          $HOME/go/bin/go${GO_VERSION} download
          export GOROOT=$($HOME/go/bin/go${GO_VERSION} env GOROOT)
          export PATH=$GOROOT/bin:$HOME/go/bin:$PATH
          make go-dependencies

      - name: Build & Test
        # Test + vulnerability check in serial.
        # We don't want the interlacing error report making troubleshooting difficult.
        run: |
          export GOROOT=$($HOME/go/bin/go${GO_VERSION} env GOROOT)
          export PATH=$GOROOT/bin:$HOME/go/bin:$PATH
          make test vulncheck-verbose

      - name: Assemble
        # Assembly builds across all platforms and can take forever.
        # This runs in parallel, which is usually fine if the tests pass.
        run: |
          export GOROOT=$($HOME/go/bin/go${GO_VERSION} env GOROOT)
          export PATH=$GOROOT/bin:$HOME/go/bin:$PATH
          make all -j$(nproc)


  test-deployment:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
      
      - name: Install OS dependencies
        # The base setup should already have many of these installed, but this makes it explicit.
        # It also sets up the qemu emulation for ARM64 processors.
        run: |
          set +x
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y \
              libbtrfs-dev libassuan-dev libgpgme-dev \
              zip \
              golang \
              make \
              buildah podman \
              qemu-user-binfmt \
              binfmt-support
          sudo update-binfmts --enable qemu-aarch64

      - name: Build
        run: |
          go install golang.org/dl/go${GO_VERSION}@latest
          $HOME/go/bin/go${GO_VERSION} download
          export GOROOT=$($HOME/go/bin/go${GO_VERSION} env GOROOT)
          export PATH=$GOROOT/bin:$HOME/go/bin:$PATH
          make build
      
      - name: Push to Repo
        # The actual test.
        # This uses buildah to create the images in the remote repository.
        # The imgoin tool creates a manifest image, also in the remote repository,
        # referencing the just created ones.
        # Then, for validation, the buildah tool pulls that image back down.
        run: |
          cd examples/remote-push
          echo "Testing imgoin built."
          ../../imgoin --version
          echo "Constructing and starting registry."
          buildah build -t local-registry Dockerfile.registry .
          podman run --rm --detatch --name registry -p 39443:39443 local-registry
          echo "Ensuring registry works."
          buildah login --tls-verify=false --username that --password thing localhost:39443
          echo "Building test images."
          buildah build -t hello-world:amd64 --platform linux/amd64 .
          buildah build -t hello-world:arm64 --platform linux/arm64 .
          echo "Pushing amd64 & arm64 into registry."
          buildah push --tls-verify=false hello-world:amd64 docker://localhost:39443/hello-world:amd64
          buildah push --tls-verify=false hello-world:arm64 docker://localhost:39443/hello-world:arm64
          echo "Testing imgoin push into the registry."
          ../../imgoin \
            --source skip-tls-verify=yes image=docker://localhost:39443/hello-world:amd64 \
            --source skip-tls-verify=yes image=docker://localhost:39443/hello-world:arm64 \
            --target skip-tls-verify=yes image=docker://localhost:39443/hello-world:latest
          echo "Validating that the push worked."
          buildah pull --tls-verify=false docker://localhost:39443/hello-world:latest
          podman kill registry
